### ISSUE TITLE
Search not working after jQuery update

### ISSUE THREAD

**Issue by jchristopher** [jchristopher/cms-tree-page-view#3]
Original issue: https://wordpress.org/support/topic/search-not-working-with-5-5-it-seems-2/

Explanation:

> I found a (temporary) solution for this problem.
> 
> The primary cause is that WordPress 5.5 changed the versions of jQuery and the way it is supported.
>
> The WordPress Team made a plugin called “Enable jQuery Migrate Helper” that solves this problem. It basically enables an older version of jQuery. You can download the plugin from https://wordpress.org/plugins/enable-jquery-migrate-helper/ Download and enable the plugin and it will work.
>
> The whole story on jQuery in WordPress on https://wptavern.com/major-jquery-changes-on-the-way-for-wordpress-5-5-and-beyond
>
> The future plugin should be changed to a newer jQuery version.
>
> Hope this will solve your problems.

**Comment by jaapwiering** [comment]
Hi Jonathan, have just test, works well, thanks!
